### ISSUE TITLE
Question:  simple-statistics in angularJS

### ISSUE THREAD

**Issue by ottigerb** [simple-statistics/simple-statistics#102] opened 2015-06-05 10:01 UTC
Just by loading 
```HTML
    <!-- Angular Dependencies -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.9.4/angular-material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/angular.moment/0.10.1/angular-moment.min.js"></script>
     <script src="scripts/app.js"></script>
    <script src="scripts/controllers/main.js"></script>
    <script src="bower_components/simple-statistics/src/simple_statistics.js"></script>
```

I end up with a 
```Uncaught TypeError: Cannot set property 'ss' of undefined```

So my question is how to use your ```simple-statistics``` in angularJS?  Ideally I don't want to touch simple_statistics.js so we can update.   Thanks for pointing me in the right direction!  Many thanks!

**Comment by ssuarezbe** [comment] 2015-07-01 03:13
It is a general bug and is not related with angular.
Check this solution: https://github.com/tmcw/simple-statistics/issues/98

I'm using AngularJS and it works.

**Comment by tmcw** [comment] 2015-07-27 20:15
Yep, this is a duplicate of #98 - the last release was broken when pulled into a strict-mode environment.

**Closed by tmcw** 2015-07-27 20:15 UTC
