### ISSUE TITLE
Possible Bug when calculating multiple quantiles

### ISSUE THREAD

**Issue by mhuttner** [simple-statistics/simple-statistics#262] opened 2017-11-17 17:12 UTC
Hello, 

When executing the following code a get a discrepancy
```js
const data = [8.15462, 8.19964, 8.20248, 8.26797, 8.2742, 8.33893];
const quants = ss.quantile(data, [0.25, 0.5, 0.75]);
console.log(quants)
// -> [null,8.23834,8.33893]
const q25 = ss.quantile(data, 0.25);
const q50 = ss.quantile(data, 0.5);
const q75 = ss.quantile(data, 0.75);
console.log([q25, q50, q75]);
// -> [8.19964,8.235225,8.2742]
```
I would expect both of these ways to return equal results?!

**Comment by tmcw** [comment] 2017-11-17 17:19
cc @mourner this might be something you recognize?

**Comment by dsaxton** [comment] 2021-03-03 23:37
Is this fixed on master? I can't reproduce:
```js
> data
[ 8.15462, 8.19964, 8.20248, 8.26797, 8.2742, 8.33893 ]
> ss.quantile(data, [0.25, 0.5, 0.75])
[ 8.19964, 8.235225, 8.2742 ]
> ss.quantile(data, 0.25)
8.19964
> ss.quantile(data, 0.5)
8.235225
> ss.quantile(data, 0.75)
8.2742
```

**Comment by mourner** [comment] 2021-03-04 09:11
Yeah, this was likely fixed at the time by https://github.com/simple-statistics/simple-statistics/pull/334 — let's close if there are no failing test cases.

**Closed by mourner** 2021-03-04 09:11 UTC
